services:
  attractor:
    container_name: attractor
    build:
      context: .
      target: attractor
    secrets:
      - ca_cert
    environment:
      - MQ_LOGIN=${MQ_LOGIN}
      - MQ_PASSWORD=${MQ_PASSWORD}
    links:
      - mq:mq
    depends_on:
      - mq
  api:
    container_name: cryptoquotes
    build:
      context: .
      target: cryptoquotes
      args:
        - API_PORT=${API_PORT}
    ports:
      - ${API_PORT}:${API_PORT}
    secrets:
      - ca_cert
      - api_cert
      - api_key
    environment:
      - MQ_LOGIN=${MQ_LOGIN}
      - MQ_PASSWORD=${MQ_PASSWORD}
      - COINMARKETCAP_API_KEY=${COINMARKETCAP_API_KEY}
    links:
      - mq:mq
    volumes:
      - /etc/ssl/certs:/etc/ssl/certs
    depends_on:
      - mq
  mq:
    container_name: mq
    image: rabbitmq:3.12-management
    ports:
      - 15672:15672
      - 5672:5672
      - 5671:5671
    volumes:
      # - ./configs/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - mq:/var/lib/rabbitmq
    secrets:
      - ca_cert
      - mq_cert
      - mq_key
    environment:
      - RABBITMQ_DEFAULT_USER=${MQ_LOGIN}
      - RABBITMQ_DEFAULT_PASS=${MQ_PASSWORD}
      # - RABBITMQ_CONFIG_FILE=/etc/rabbitmq/rabbitmq.conf
volumes:
  mq:
secrets:
  ca_cert:
    file: ${CA_CERT_PATH}
  api_cert:
    file: ${API_CERT_PATH}
  api_key:
    file: ${API_KEY_PATH}
  mq_cert:
    file: ${MQ_CERT_PATH}
  mq_key:
    file: ${MQ_KEY_PATH}
